language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- mvn clean package dockerfile:build dockerfile:push
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - secure: S8uFL6emXuZ6zTB3b5kTKjVYpVhfHxVrDFSeMqg2EIWom0+u0AvoKclAXDWprMuHMr0dNcF8EcuOQrF7J6MQuj6j4zUQqsZopPQiimJLOUmn0A5EWTgHx2sue6FPj6ajkQ1QxEQEYOp4DGh7ddGSQqTvSCMj7QVyvHsRlRyRO4+VPneF9VQw4k8FKniKctFYXLxi8eZi/g3DwArrbbiW1zkW6soPxWC5FsqpYnAHw8eEBKWNSSlK3ZlertkRG4FjMvLwDxdZHzbNuZF00QSbvBVBoxX1TA3bDJnFnkSq5SjrtSjpxrvaZdwNrPaBh1sV9h6FUamN70isqEkRrby5m39uGyONaTD/JQlsI+alLDTv0mOKvtOUrAF5JP8lBfGcgY1z20nhL/Gkk9A0zRLSkX1D66B9zLrw6vrpkajPCw/yxi03Cm2sY7IgoqviSuwX9gQ1ywZOKD/j+chh7GSsNIJ/c0VrNmdxlPe6qHawkNOMl1gnOioccFYFGQdGuLiWDbH3CFObTl39cAAQOCo8hPOJFhJNS5ags+6ELG8MV0n795TxTKsv6M2CRa+1tW2+GGwokZefYHC9wRbrjGdvT45fJ8B4jSNERS/5VpSe4Z2MnuzP8LFAN9MvpnKyqYZ5GHpC/IEFuTZ82PI0gBO11MIREoXJwu1cJsY5Bgq3ddQ=
  - secure: rs9OSSQJX6H3xYOqlLunL6y3ypL4zV5BxqZc6OYRSzlSPblCrM0aquVndB83InOEppI8P/gs1R0RzYaeQ7VL2Un0qkh/aSyEYl51Ct4Nw0S5qqTZKbb2eWj/igFKyv7zBkw2PBo21k141UOEkjrMjltpdWQ17xSwV6K+B6FDARnNqXoy98IAr32yWGEBQN+r2nruq0BLxqfpBI5a87drXp5zCNterQQl5TlMjfT6g7h0ZpKYm1NN3Gr+hoafzytGBsr7II+IlD0bqaj3btREI9HCxrAiYEknTplBz6AFURk3nW0otM9FxvniGayL05+H14arVQqh865qvgzEq9j7RfRGTX4XaNd6uMpCjX6fD4fRwHrqaNBs9UvA8cXLsus+BpaKWiV3XMsK7ix1IR0WQg6CSnZdikWUvrPPkU7jrHy/v/s5H328BK7LjltiOav6qXcv/FQqS6vOdGjaozhOheT88x0dVbzPlpcYf1wV6/k+HtbRwg9stJsNCd3XMACg+H78IxAYM7Q2rtIW0DUIyriCIL5WXbmMJl8k5VIV2mlKcHh1ufg0JJLsqt6vviTgHUGFStT7bCQlHz+MB38K511Kd9fAlfgf5s03N9eSZWaDNT9jD2P7/SIBMXMaaIa1IjJWPkFmD7D1062FiByGDO+q9nUOB24fic5uxUm+qw4=
