language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- mvn clean package dockerfile:build dockerfile:push
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - secure: WvZa7JFhISdKwZjF6Ayaw/D5g9dF0OYgB7/gVsFWOQK3lXIAqXBQOx1wh4WExZC778yeCPyGbWhxCxfpRImhtT4Psy1cL0/7tfjZ+MCdgBheCIIm8rh197SsEDjos5d8abxh159nJdkgwWn3F70eHll2mRhv05hul00vWc9giMvw3pYDR9Kn99qif7t5kLk2CMBJdB6Ui4y5QFnVqi2eJEbntJ+MaL769uaeuLHDP4//73CxMMN1WG8tv8iRRM19iG5FvM1PknZq1VHkCAxLfACRnE3wjrH68NCeg9u4gHMsy9XIV8qJf9msE7VJMJi5QOLXbuuzq0mg1a+mtBW/08rin18gpEShMe2WqXl9qHZcduP5GHE2l0OtxzRo82mQrjDyk+5Bl2zdN/q6t4X95GgOi8QJF8+HVkh/Vvyub0tmYN6J4WSeLXnMLOWGigQGxZ7UbC89HCgkfnptvjDPMhXtWofwggibugz7mrQsVoZRxmyVWj6ao5xJeGbU/sGj5QDZvbYRVz7KeMZzwR6+oFFXqoo9iHwydD++WjOsS29bVTWxnDPqDleTbEDFWwzDuJSLuANJUAeTBVXrIwcJn/tQqhZGMv6kwFuToETyKoOqu0UbB1Q7yFkQ2/2mfIt0418JUwhhgLcTnPcF8Q5bc3Bv2Z6WII7ibClJBYuB3Kc=
  - secure: HU82zN2lOMOCZ2yu8cOyZdR9T345YVeOFgPM+yhtu3kIlQTmk71XG6hqGX0LrCzaJGOXZr0eCpTzizpMx0cZM8vXMSEi4u6hxIESnXq7LXw16x+A1WYiJm0wRNtR9fePR8SE1FsmVsBkfWYCGNotzpaAWaFnN4omiHexAU7XLII0qxtCTY/ZW+mtvv8OZdVSF+Sem6tWgoOp2gjT68nCielv+R4yNVkt4PlhWf8dU5DC+RXNWeBuGinoQSyxP6vCkm4kotJlfXtzlRyo60MaIGkKrXliwUZKnftT6JUuDgShzOdAgrq5aiLDVVPzclBKDmABGMz4KUPkFXQ92oCVkmIi+RmMgd+YpFTWVCUhGsPAMD3x5QO/lxLF/ORKcGg649faXvdMHzzsXiXfh2/Kfgj61AETltdmi+VXlY1Cc6MKKvyyns/8cETeaxUMuAFmtgDpmQv8MWPsTzok4KmCxNK4FQ29rMGnPoT14YYasOU+NNYHiyvM8+pItADvoxJ0BOtIYvGt9L9za6l3S37MHUtP3LXU8IZBredux9SDmo2WliirfJvsP5bER2We+dUjapVrcH5bU/1lGQ/HscNmOlMT0aujboPGmLoaypcbV/QAPyCcD3Pgx2QPzzX/C6zlemDM5mVG2D8Fb/BfZBXeIIdTvczvb3xNgQNri/48PFc=
