language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- mvn clean package dockerfile:build dockerfile:push
before_install:
- chmod +x mvnw
notifications:
  email:
    on_success: never
    on_failure: never
env:
  matrix:
  - secure: LLSZA11K0Bc1h3x13Mppx1xltNg7agIguI9gw1gPqhBqh7QRDLTFANAocWHc77BO81RebzlKnC1hHhZCYA3VaABT0jpCNgE/vOGn7yvc3U9VejeQ5J149BWSdlJE9s6AqNePVUSCXDHo9ZdEPBHbh9la5BF0jF2vHLHI4r7QU8mFsp3wKJpDzg11axa48oMzShA731fzbddAb6UM/QtbBa80e52ExniWAxpqr60lZukVAQHn7l51NTxvRstFPo539mq6b0hyGMkuiTyQdGlsKgsUME8ZPSkFm3WKhF4NlpR4Yr+wF4ELlxMHVt6GOgznjRlO3tZbp0UyxfByV4AOHr7rrGCeUladGaGgt9GSEKwzKTp3nRx+r7MuEdP7kvgcyWJBOI6oRkfcuyuCQH4HuCvxFFpzGlv2luGPh9wpivT4MHJgS9sHLTrS/mEdNSiYPhAw1pNfY7QLZLbyBLYrrguL55bWZAfRodk2MbDLfQW+P5kMBQQ21eqnDlS/sdPJV9+zoUP5ad9CoQ/tkKJBjgaYA8cFB7YMqeZjsasA+VJHcSoiGHSzQdo2Yisf+/uZbck19tiAt85/GPdsVOmiEsEYjyw9vYI/SVU2maloK8jh8RtNd04GfhLuTHN0WUcGF9vZfcIej2EqZZZ1QRpm89vmGuH+9Ilhf4bAWJeiAnI=
  - secure: j0QHiGgGPs8E8YRJDlxAFc49sOx7xA2ctZDxA2BS3PJh3DY/l38erzGy9C8juYGiEa45bomeatLI85MzKMXvWahceJAmav8699FeX7YWDwVe+fjwZurgLg5z+wYT6ZSzbZRkDTXmJ//LiMGC7wdNqqPKiJAefuuG6Gehv5EaqOIxCJP8keeVkLmFjRgDX2R7Lyr25wlN6l1UyO3eLAQWjN4atUAHWepWbC5hUkeRPENpENfATlgx2MriGn7gKMwqEeMWKjyq5f/6rcXCC77khYIz1k8f/0CXPke0dv5VWJgJ/mlCeAojBtWQOz96yk7xYsNbqr8jwNxsMbe+HxlC9GJKWGcmfaW0Qxgn3ml/jW1J1g3lCOCS1I1Jh1Jr/Msxt5A6cBS5B7wwAObIXkoFvFzZUd4DxdQht8E030SUxpK57Ffxtt5TB7hs0hD0V0DCSwK1xLNeUihBl/o6p0p+pMkPNpIBhjbUcT3OqAsuaeTRw0LBXaSYg7fP2ZAeNR0pfQgM79p/6PIKCLIde44pXJfMmcA8rZG2Scd/2eiX5No8HKcSQrIToM1lel6YIWec6gFGCRHM1fwaWT017/2pc/otLGTwUX0XATiZTi0Lgii37XsfxhPWtO8JA+spWobm7dB0xiiprlo3mATaRA3zwb7o7MRapxNpHRctsavYI04=
